### ISSUE TITLE
Example Code doesn't use &state for CSRF?

### ISSUE THREAD

**Issue by auxiliary-character** [Patreon/patreon-python#10]
[The documentation](https://www.patreon.com/platform/documentation/oauth) recommends using `&state` for CSRF in step 1, but the [example code](https://github.com/Patreon/patreon-python/blob/master/examples/flask/my_site/app/controllers/auth_controller.py#L25-L46) doesn't appear to use it. Is this a security problem?

**Comment by phildini** [comment]
Thanks for asking, sorry it took us so long to reply. Whether or not it's a bug, it's certainly unclear, and we'll adjust the examples in a future version to make it clearer.
