### ISSUE TITLE
Error on example page

### ISSUE THREAD

**Issue by deadmaus3221** [Patreon/patreon-python#16]
Hi. I'm trying to run the example page to understand better how this api works, and I'm not having success.

I'm getting KeyError: 'refresh_token' error, and I don't know why. My patreon_creator_refresh_token is right.

LOG: https://pastebin.com/KaZV0PXU

Config file: https://pastebin.com/NgTTNf4G

**Comment by deadmaus3221** [comment]
I don't know if it matters, but on my Client I had to put a fake Company Domain, because it doesn't accept ip adresses, I don't know if it matters

**Comment by phildini** [comment]
Hi there! Sorry for the long delay. Could you try again with the updated example in the repo and see if you still have the same problem? Thanks!

**Comment by emosesPatreon** [comment]
Closing, assuming this is fixed with updates to example.  Please re-open if you're still having trouble.
