### ISSUE TITLE
Error in extract_cursor() method

### ISSUE THREAD

**Issue by hate5six** [Patreon/patreon-python#19]
I'm attempting to replicate the example here for retrieving all pledges to a campaign: https://docs.patreon.com/?python#fetch-a-creator-profile-and-campaign-info

```
import patreon

access_token = nil # your Creator Access Token
api_client = patreon.API(access_token)

# Get the campaign ID
campaign_response = api_client.fetch_campaign()
campaign_id = campaign_response.data()[0].id()

# Fetch all pledges
all_pledges = []
cursor = None
while True:
    pledges_response = api_client.fetch_page_of_pledges(campaign_id, 25, cursor=cursor)
    pledges += pledges_response.data()
    cursor = api_client.extract_cursor(pledges_response)
    if not cursor:
        break
```
However, I get the following error (I'm using a valud access_token):

> Traceback (most recent call last):
  File "get_patrons.py", line 16, in <module>
    cursor = api_client.extract_cursor(pledges_response)
  File "/home/hate5six/hate5six.com/h5senv2.7/lib/python2.7/site-packages/patreon/api.py", line 74, in extract_cursor
    'Provided cursor path did not result in a link', current_dict
Exception: ('Provided cursor path did not result in a link', u'https://www.patreon.com/api/oauth2/api/campaigns...')

**Comment by hunganh0403** [comment]
I have same problem and got a work around solution, hope it'll help until they fix this:
````python
from urlparse import urlparse, parse_qs
cursor = parse_qs(urlparse(pledges_response['links']['next']).query)['page[cursor]'][0]
````

**Comment by hate5six** [comment]
@hunganh0403 interesting. What is the pledges_response object in your example? I'm using the code from the demo so it's a JSONAPIParser object. It doesn't have a get method so pledges_response['links']['next'] fails.

**Comment by hunganh0403** [comment]
pledges_response.json_data will do
I've edited in my comment

**Comment by phildini** [comment]
Hey there! Thanks for writing in, we're going to look into this.

**Comment by mubix** [comment]
Same issue, any updates?

**Comment by phildini** [comment]
Hey there. I'm really sorry we've been so delayed on getting this fixed; I'm hoping we'll have an answer for you all this week!

**Comment by lynneatan** [comment]
Hi everyone, I am closing this issue as this problem should now be fixed in the latest version.
