### ISSUE TITLE
Discord compatability...?

### ISSUE THREAD

**Issue by lpkeates** [Patreon/patreon-python#31]
I don't really know how to use the API with Discord.py, but I want it so there is like a patreon-discord thingy. It could be in discord.py or discord.js etc.

**Comment by DrLarck** [comment]
Hey !

Lucky you, I've finished my **Patreon** integration for my **discord bot** yesterday.

Here's the code I wrote : https://github.com/DrLarck/DragonBotZ/blob/master/utility/entity/patreon.py

If you have any questions, do not hesitate to ask them !

Happy coding ;)

**Comment by lpkeates** [comment]
> Hey !
> 
> Lucky you, I've finished my **Patreon** integration for my **discord bot** yesterday.
> 
> Here's the code I wrote : https://github.com/DrLarck/DragonBotZ/blob/master/utility/entity/patreon.py
> 
> If you have any questions, do not hesitate to ask them !
> 
> Happy coding ;)

Thanks so much! Without you, how the actual heck would I be unable to do this? <3
