### ISSUE TITLE
Hi, Using Python 3.8 with Django and Patreon Having an issue with get_identity from the API class

### ISSUE THREAD

**Issue by ZeroPointGaming** [Patreon/patreon-python#33]
def PComplete(request): #catch the return from the patreon oauth site, sanitize data, pass data to demplate, redirect back to home page, somehow cache the data??
	print(request.GET.get('code'))

	oauth_client = patreon.OAuth(client_id, client_secret)
	access_token = request.GET.get('code')

	api_client = patreon.API(access_token)
	user_response = api_client.get_identity()
	user = user_response.data()
	print(user)
	memberships = user.relationship('memberships')
	membership = memberships[0] if memberships and len(memberships) > 0 else None

	return render(request, 'dashboard.html', {'p_user' : user, 'p_member' : membership})

Here is my views request, everything works prefectly up until the point where apiclient.get_identity() is called, this occurs.

AttributeError at /accounts/patreon/login/callback/
'API' object has no attribute 'get_identity'

Patreon and its requirements (requests, six) are installed via pip3 all in a virtual env with the project

Maybe I am doing something wrong, Any help would be appreciated.

**Comment by ZeroPointGaming** [comment]
Yes I am importing patreon at the top of the file.

**Comment by ZeroPointGaming** [comment]
pip3 installed the following version: Using cached patreon-0.5.0-py3-none-any.whl

**Comment by ZeroPointGaming** [comment]
Noticed this is an ongoing issue with release 0.5.0

**Comment by frederikme** [comment]
@ZeroPointGaming how did you fix it?

**Comment by frederikme** [comment]
For future reference:
Installing the latest GitHub version fixed it for me.
This can be done using pip as following.
`pip install git+https://github.com/Patreon/patreon-python`
